--Cada tabla solamente puede tener un solo CLUSTERED
  CREATE CLUSTERED INDEX NOMBREINDEX ON INTERACTION (ID);
  --1 Tabla puede tener Muchos NONCLUSTERED
  CREATE NONCLUSTERED INDEX NOMBREINDEX ON INTERACTION (ENdDate, StartDate);